//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XtremeMobiles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public int Id { get; set; }
        public string resolution { get; set; }
        public string camera { get; set; }
        public string ram { get; set; }
        public string rom { get; set; }
        public string cpu { get; set; }
        public string os { get; set; }
        public string wifi { get; set; }
        public string model { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
